[program:crm-pro-web]
command=/home/frappe/frappe-bench/env/bin/gunicorn -b 127.0.0.1:8000 -w 4 frappe.app:application --preload
directory=/home/frappe/frappe-bench/sites
user=frappe
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/crm_web.log
stderr_logfile=/var/log/supervisor/crm_web_error.log

[program:crm-pro-worker]
command=/home/frappe/frappe-bench/env/bin/bench worker --queue default,short,long
directory=/home/frappe/frappe-bench
user=frappe
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/crm_worker.log
stderr_logfile=/var/log/supervisor/crm_worker_error.log

[program:crm-pro-scheduler]
command=/home/frappe/frappe-bench/env/bin/bench schedule
directory=/home/frappe/frappe-bench
user=frappe
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/crm_schedule.log
stderr_logfile=/var/log/supervisor/crm_schedule_error.log
